### ISSUE TITLE
bootstrap-3 templates using navbar-fixed-top

### ISSUE THREAD

**Issue by gadicc** [nate-strauser/meteor-connection-banner#2]
This isn't actually an issue with your package, but I suspect this might be a common problem for a number of people.

If the user has a fixed navbar at the top of the page, the connectionBanner will render invisibly behind it.  We could change the z-index, but it looks ugly overlaying over the navbar.  We just used the following CSS to move the navbar down if the banner is rendered (or appear below the navbar).

``` css
#meteor-connection-lost-banner + div.navbar-fixed-top,
#meteor-connection-try-reconnect + div.navbar-fixed-top {
    top: 41px;
}
div.navbar-fixed-top + #meteor-connection-lost-banner,
div.navbar-fixed-top + #meteor-connection-try-reconnect {
    top: 51px;
}
```

And insert the template either directly before or after the navbar div, e.g.:

``` html
  {{connectionBanner}}
   <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      ...
   </div>
```

Not sure if this should possibly be the default behaviour (since the package recommends using bootstrap-3), or mentioned in the README, or what you suggest?
